version: '3.8'

services:
  db1:
    container_name: pg-master
    image: bitnami/postgresql:14
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "5432:5432"
    networks:
      - mynet
    volumes:
      - pgmaster_data:/bitnami/postgresql

  db2:
    container_name: pg-replica1
    image: bitnami/postgresql:14
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    depends_on:
      - db1
    networks:
      - mynet
    volumes:
      - pgreplica1_data:/bitnami/postgresql

  db3:
    container_name: pg-replica2
    image: bitnami/postgresql:14
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=pg-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    depends_on:
      - db1
    networks:
      - mynet
    volumes:
      - pgreplica2_data:/bitnami/postgresql
  
  api-service:
    build: ./api
    networks:
      - mynet
    depends_on:
      - db1
      - db2
      - db3

volumes:
  pgmaster_data:
  pgreplica1_data:
  pgreplica2_data:

networks:
  mynet:
    driver: bridge